disabled_rules: # rule identifiers turned on by default to exclude from running
  - vertical_whitespace
  - trailing_whitespace

identifier_name:
  allowed_symbols: "_"

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
