disabled_rules: # rule identifiers turned on by default to exclude from running
  - vertical_whitespace
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods